version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: meu_projeto_edu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/meu_projeto_edu
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data: