# Generated by Django 5.2.14 on 2026-05-08 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='course',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
